### ISSUE TITLE
04/14 食事レポート

### ISSUE THREAD

**Issue by mokocm** [mokocm/diet#1]
|name|kcal|
|-----|---|
|BASE BREAD メープル|264kcal|
|モンスター|166kcal|
| 羊羹 |136kcal|
|チーズテリヤキダブルワッパー | 981kcal|
|Mフレンチフライ| 466kcal|
|Lコカコーラ |129kcal|
||2142kcal|

ref: #3

**Comment by mokocm** [comment]
## 朝ご飯(昼ご飯)
BASE BREADメープル 264kcal
![image_from_ios](https://user-images.githubusercontent.com/52817048/163317450-e2cd1520-cf39-44eb-bcd5-7d9c42fb0f6a.jpg)
モンスター新作（駅前で配ってた） 166kcal
![image_from_ios](https://user-images.githubusercontent.com/52817048/163317371-6a74fc39-695f-4a57-9519-e6b76e3e3ec0.jpg)

**Comment by mokocm** [comment]
補給食 羊羹 136kcal
![image](https://user-images.githubusercontent.com/52817048/163353603-2e62db16-f625-45a5-8545-3c8aca6cf6b9.jpeg)

**Comment by mokocm** [comment]
## 夜ご飯
チーズテリヤキダブルワッパー ????kcal
Mフレンチフライ 466kcal
Lコカコーラ 129kcal

![image](https://user-images.githubusercontent.com/52817048/163371800-251a0733-91f3-476f-b34a-d8e9f95f0f94.jpeg)

**Comment by 0x6d61** [comment]
個人的に二食を同じものにするのおすすめ
