### ISSUE TITLE
旭川まで自転車漕ぐ

### ISSUE THREAD

**Issue by r-kataoka11** [mokocm/diet#162]
# 背景
前スプの「早起きして運動する」が一回も実行されなかった。
今スプは旭川まで自転車を漕いでカロリーを消化する。

# 受け入れ条件
- [x] 旭川まで自転車で往復する
- [x] 達成できなかったら彼女に核ミサイルを共有する

**Comment by mokocm** [comment]
#173

**Comment by r-kataoka11** [comment]
往復はできなかったけど安全第一！実行して結果出したので今スプリントはOKとします。
