### ISSUE TITLE
毎日食べたものを記録して分析できるようにしたい

### ISSUE THREAD

**Issue by r-kataoka11** [mokocm/diet#2]
# 背景
もこさんが暴飲・暴食で日々増幅し続けている。
その暴飲・暴食したものを毎日記録して、何が一番カロリーが多いか等を後から分析できるようにしたい。
そして後から振り返ることができるようにしたい。

# 受け入れ条件
- [x] 毎日食べたものが記録されていること
- [x] 毎週食べたものを振り返りがスクラムイベントで実施できていること

**Comment by mokocm** [comment]
>  毎週食べたものを振り返りがスクラムイベントで実施できていること
まずはスクラムイベントとリファインメントを開催する。

スクラムイベント: 毎週木曜日 14:00 〜 14:30
リファインメント: 毎週月曜日 15:30 〜 16:00

**Comment by r-kataoka11** [comment]
SP3で継続できていたらDONEにしてもいいかも
