### ISSUE TITLE
SP1 スクラムイベント

### ISSUE THREAD

**Issue by r-kataoka11** [mokocm/diet#5]
# プランニング
- [x] 今回達成できたIssueの確認とレビュー
  - [x] なんでできなかったか今考えてください　→　できたのすごい！
- [x] 次のスプリントのゴール設定
- [x] 次のスプリントでやっていくことをSBLに積んでいく

# レトロスペクティブ
次のスプリントをやっていく動機付けになるポジティブな振り返りが望ましい。
なぜできなかったかはプランニングで原因究明して、やってできたこと・わかったこと・次トライしてみることがわかるようにしたい。

# スクラムイベントのプチ振り返り
スクラムイベント自体で改善できることを洗い出していく。

**Comment by mokocm** [comment]
開始前(2022/04/14)
![image](https://user-images.githubusercontent.com/52817048/163329655-48684ed1-64ec-4638-b810-9810e05d7650.png)

**Comment by mokocm** [comment]
![image](https://user-images.githubusercontent.com/52817048/163937190-bc036c4b-9fc1-4892-80b0-0a98792329b8.png)

**Comment by mokocm** [comment]
![image](https://user-images.githubusercontent.com/52817048/163937288-3aa76cef-ba05-4c4e-8299-f47bfd3e6810.png)

**Comment by mokocm** [comment]
うおおお
![image](https://user-images.githubusercontent.com/52817048/164116928-78eb7129-800a-48fc-a56c-15212570fa14.png)

**Comment by mokocm** [comment]
![image](https://user-images.githubusercontent.com/52817048/164340356-272ba730-0382-431a-b33d-7782bf183dff.png)

**Comment by kazuemasaki** [comment]
体脂肪が2.08kgくらい落ちてますね🙌

**Comment by mokocm** [comment]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/52817048/164419480-5495530c-0a5d-455b-80ac-f048fdb4be92.png">

**Comment by mokocm** [comment]
<img width="1421" alt="SP1レトロスペクティブ_-_Google_Jamboard" src="https://user-images.githubusercontent.com/52817048/164419685-db1d29d4-c6dc-4533-ad83-12afc6971638.png">
