### ISSUE TITLE
SP1 リファインメント

### ISSUE THREAD

**Issue by r-kataoka11** [mokocm/diet#6]
# やること
- [x] EPICの確認（内容と受け入れ条件・優先順位の確認）
- [x] INVESTに沿っているか確認（https://ja.wikipedia.org/wiki/INVEST ）
- [x] EPICに過不足がないか確認
- [x] EPICに対して実際のタスクが抜け漏れないかPBLを確認（漏れがあればIssueを追加）
- [x] プロダクトゴールに近づいているか確認
- [x] （必要があれば）プロダクトゴールの見直し（体組織計の結果を見てゴールの見直しをする）
- [x] PBLの優先順位変更
- [x] リファインメントのプチふりかえり

# リファインメントプチ振り返り
- 超ポジティブに振り返れた
- ゴール設定も現実的なラインでもうちょっとで達成できそう
- iPadわかりやすい

**Comment by mokocm** [comment]
![image](https://user-images.githubusercontent.com/52817048/163738442-ec411058-9f9d-4b98-9192-6c272253ceee.png)

**Comment by r-kataoka11** [comment]
開始時の体脂肪
https://github.com/mokocm/diet/issues/5#issuecomment-1098768782
